package org.parasol.claim.seed;

import java.io.IOException;
import java.io.InputStream;
import java.util.EnumMap;
import java.util.List;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Collectors;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Observes;
import jakarta.transaction.Transactional;

import org.parasol.claim.model.Claim;
import org.parasol.claim.model.ClaimImage;
import org.parasol.claim.model.ClaimImageContentType;
import org.parasol.claim.model.ClaimImageKind;

import io.quarkus.logging.Log;
import io.quarkus.runtime.StartupEvent;

/**
 * Attaches the sample images to the six claims seeded by {@code import.sql}.
 * <p>
 * Runs on every start and inserts each configured image its claim doesn't have yet, so it's idempotent and also
 * restores images that were deleted. Seed data never fails startup: an image whose claim doesn't exist, or whose
 * resource file is missing, unreadable or empty, is logged and skipped, and the other images are still seeded.
 * Claims are matched by their explicit ids from {@code import.sql}: claim numbers are generated by a database sequence,
 * so they can't be known here.
 */
@ApplicationScoped
class ClaimImageSeeder {
	static final String RESOURCE_DIRECTORY = "/seed/claim-images/";

	static final List<SeedImage> SEED_IMAGES = List.of(
		new SeedImage(1L, ClaimImageKind.ORIGINAL, "original_car1.jpg"),
		new SeedImage(1L, ClaimImageKind.PROCESSED, "car1-processed.jpg"),
		new SeedImage(2L, ClaimImageKind.ORIGINAL, "original_car2.jpg"),
		new SeedImage(2L, ClaimImageKind.PROCESSED, "car2-processed.jpg"),
		new SeedImage(3L, ClaimImageKind.ORIGINAL, "original_car3.jpg"),
		new SeedImage(3L, ClaimImageKind.PROCESSED, "car3-processed.jpg"),
		new SeedImage(4L, ClaimImageKind.ORIGINAL, "original_car4.jpg"),
		new SeedImage(4L, ClaimImageKind.PROCESSED, "car4-processed.jpg"),
		new SeedImage(5L, ClaimImageKind.ORIGINAL, "original_car5.jpg"),
		new SeedImage(5L, ClaimImageKind.PROCESSED, "car5-processed.jpg"),
		new SeedImage(6L, ClaimImageKind.ORIGINAL, "original_car6.jpg"),
		new SeedImage(6L, ClaimImageKind.PROCESSED, "car6-processed.jpg")
	);

	void onStart(@Observes StartupEvent event) {
		seed(SEED_IMAGES);
	}

	/**
	 * Inserts each of the given images that its claim doesn't have yet, skipping (and logging) any that can't be
	 * seeded.
	 *
	 * @param seedImages the images to seed
	 * @return the count of each outcome, which is also logged as a one-line summary
	 */
	@Transactional
	SeedResult seed(List<SeedImage> seedImages) {
		var outcomes = seedImages.stream()
			.map(this::seedIfMissing)
			.collect(Collectors.groupingBy(Function.identity(), () -> new EnumMap<>(SeedOutcome.class), Collectors.counting()));

		var result = new SeedResult(
			outcomes.getOrDefault(SeedOutcome.INSERTED, 0L),
			outcomes.getOrDefault(SeedOutcome.ALREADY_PRESENT, 0L),
			outcomes.getOrDefault(SeedOutcome.CLAIM_NOT_FOUND, 0L),
			outcomes.getOrDefault(SeedOutcome.IMAGE_UNREADABLE, 0L)
		);

		Log.infof(
			"Processed %d seed claim images: %d inserted, %d already present, %d claim not found, %d file missing/unreadable/empty",
			seedImages.size(),
			result.inserted(),
			result.alreadyPresent(),
			result.claimNotFound(),
			result.imageUnreadable()
		);

		return result;
	}

	private SeedOutcome seedIfMissing(SeedImage seedImage) {
		return Claim.<Claim>findByIdOptional(seedImage.claimId())
			.map(claim -> ClaimImage.hasImage(claim, seedImage.kind(), seedImage.fileName()) ? SeedOutcome.ALREADY_PRESENT : insert(claim, seedImage))
			.orElseGet(() -> skip(seedImage, SeedOutcome.CLAIM_NOT_FOUND, "claim %d doesn't exist".formatted(seedImage.claimId())));
	}

	// The file is read only here, after the claim is known to exist and to be missing this image
	private static SeedOutcome insert(Claim claim, SeedImage seedImage) {
		var resourcePath = RESOURCE_DIRECTORY + seedImage.fileName();

		return readImage(resourcePath)
			.map(data -> {
				ClaimImage.store(claim, seedImage.kind(), seedImage.fileName(), ClaimImageContentType.JPEG, data);
				return SeedOutcome.INSERTED;
			})
			.orElseGet(() -> skip(seedImage, SeedOutcome.IMAGE_UNREADABLE, "resource %s is missing, unreadable or empty".formatted(resourcePath)));
	}

	// Empty if the resource is missing, can't be read or is empty (an empty image would fail validation at flush and roll
	// back the whole run)
	private static Optional<byte[]> readImage(String resourcePath) {
		return Optional.ofNullable(ClaimImageSeeder.class.getResourceAsStream(resourcePath))
			.flatMap(stream -> readAllBytes(stream, resourcePath))
			.filter(data -> data.length > 0);
	}

	private static Optional<byte[]> readAllBytes(InputStream stream, String resourcePath) {
		try (stream) {
			return Optional.of(stream.readAllBytes());
		}
		catch (IOException e) {
			Log.debugf(e, "Couldn't read seed image resource %s", resourcePath);
			return Optional.empty();
		}
	}

	private static SeedOutcome skip(SeedImage seedImage, SeedOutcome outcome, String reason) {
		Log.warnf("Skipping seed image %s for claim %d: %s", seedImage.fileName(), seedImage.claimId(), reason);

		return outcome;
	}

	/**
	 * An image to attach to a seeded claim. The file lives under {@value #RESOURCE_DIRECTORY} on the classpath.
	 *
	 * @param claimId the id of the seeded claim in {@code import.sql}
	 * @param kind the image kind
	 * @param fileName the file name under {@value #RESOURCE_DIRECTORY}
	 */
	record SeedImage(long claimId, ClaimImageKind kind, String fileName) {
	}

	/**
	 * What one {@link #seed(List)} run did. Startup only logs it; tests assert it, because "already present" and "claim
	 * not found" leave nothing in the database to check.
	 *
	 * @param inserted images inserted
	 * @param alreadyPresent images the claim already had
	 * @param claimNotFound images skipped because their claim doesn't exist
	 * @param imageUnreadable images skipped because their resource file is missing, unreadable or empty
	 */
	record SeedResult(long inserted, long alreadyPresent, long claimNotFound, long imageUnreadable) {
	}

	private enum SeedOutcome {
		INSERTED,
		ALREADY_PRESENT,
		CLAIM_NOT_FOUND,
		IMAGE_UNREADABLE
	}
}