package org.parasol.claim.seed;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.util.List;
import java.util.Optional;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Observes;
import jakarta.transaction.Transactional;

import org.parasol.claim.model.Claim;
import org.parasol.claim.model.ClaimImage;
import org.parasol.claim.model.ClaimImageContentType;
import org.parasol.claim.model.ClaimImageKind;

import io.quarkus.logging.Log;
import io.quarkus.runtime.StartupEvent;

/**
 * Attaches the sample images to the six claims seeded by {@code import.sql}.
 * <p>
 * Runs on every start and inserts each configured image its claim doesn't have yet, so it's idempotent and also
 * restores images that were deleted. A claim that doesn't exist is logged and skipped rather than failing startup.
 * Claims are matched by their explicit ids from {@code import.sql}: claim numbers are generated by a database sequence,
 * so they can't be known here.
 */
@ApplicationScoped
class ClaimImageSeeder {
	static final String RESOURCE_DIRECTORY = "/seed/claim-images/";

	static final List<SeedImage> SEED_IMAGES = List.of(
		new SeedImage(1L, ClaimImageKind.ORIGINAL, "original_car1.jpg"),
		new SeedImage(1L, ClaimImageKind.PROCESSED, "car1-processed.jpg"),
		new SeedImage(2L, ClaimImageKind.ORIGINAL, "original_car2.jpg"),
		new SeedImage(2L, ClaimImageKind.PROCESSED, "car2-processed.jpg"),
		new SeedImage(3L, ClaimImageKind.ORIGINAL, "original_car3.jpg"),
		new SeedImage(3L, ClaimImageKind.PROCESSED, "car3-processed.jpg"),
		new SeedImage(4L, ClaimImageKind.ORIGINAL, "original_car4.jpg"),
		new SeedImage(4L, ClaimImageKind.PROCESSED, "car4-processed.jpg"),
		new SeedImage(5L, ClaimImageKind.ORIGINAL, "original_car5.jpg"),
		new SeedImage(5L, ClaimImageKind.PROCESSED, "car5-processed.jpg"),
		new SeedImage(6L, ClaimImageKind.ORIGINAL, "original_car6.jpg"),
		new SeedImage(6L, ClaimImageKind.PROCESSED, "car6-processed.jpg")
	);

	void onStart(@Observes StartupEvent event) {
		seed(SEED_IMAGES);
	}

	/**
	 * Inserts each of the given images that its claim doesn't have yet.
	 *
	 * @param seedImages the images to seed
	 * @return the number of images inserted
	 */
	@Transactional
	long seed(List<SeedImage> seedImages) {
		var inserted = seedImages.stream()
			.filter(this::seedIfMissing)
			.count();

		Log.infof("Seeded %d of %d claim images", inserted, seedImages.size());

		return inserted;
	}

	private boolean seedIfMissing(SeedImage seedImage) {
		var claim = Claim.<Claim>findByIdOptional(seedImage.claimId());

		if (claim.isEmpty()) {
			Log.warnf("Skipping seed image %s: claim %d doesn't exist", seedImage.fileName(), seedImage.claimId());
		}

		return claim
			.filter(c -> !ClaimImage.hasImage(c, seedImage.kind(), seedImage.fileName()))
			.map(c -> ClaimImage.store(c, seedImage.kind(), seedImage.fileName(), ClaimImageContentType.JPEG, readImage(seedImage.fileName())))
			.isPresent();
	}

	private static byte[] readImage(String fileName) {
		var resourcePath = RESOURCE_DIRECTORY + fileName;

		try (var stream = Optional.ofNullable(ClaimImageSeeder.class.getResourceAsStream(resourcePath))
			.orElseThrow(() -> new SeedImageNotFoundException(resourcePath))) {

			return stream.readAllBytes();
		}
		catch (IOException e) {
			throw new UncheckedIOException("Couldn't read seed image %s".formatted(resourcePath), e);
		}
	}

	/**
	 * An image to attach to a seeded claim. The file lives under {@value #RESOURCE_DIRECTORY} on the classpath.
	 *
	 * @param claimId the id of the seeded claim in {@code import.sql}
	 * @param kind the image kind
	 * @param fileName the file name under {@value #RESOURCE_DIRECTORY}
	 */
	record SeedImage(long claimId, ClaimImageKind kind, String fileName) {
	}

	/**
	 * Thrown when a configured seed image is missing from the classpath. That's a packaging bug, so it fails startup.
	 */
	static class SeedImageNotFoundException extends IllegalStateException {
		SeedImageNotFoundException(String resourcePath) {
			super("Seed image resource %s was not found".formatted(resourcePath));
		}
	}
}