---
openapi: 3.1.2
components:
  schemas:
    Instant:
      type: string
      format: date-time
      examples:
        - 2022-03-10T16:15:50Z
    InteractionEvent:
      type: object
      discriminator:
        propertyName: interactionType
        mapping:
          started: "#/components/schemas/InteractionStartedEvent"
          completed: "#/components/schemas/InteractionCompletedEvent"
      properties:
        interactionId:
          $ref: "#/components/schemas/UUID"
        interactionDate:
          $ref: "#/components/schemas/Instant"
        interfaceName:
          type: string
        methodName:
          type: string
        interactionType:
          type: string
        applicationName:
          type: string
        interactionMode:
          $ref: "#/components/schemas/InteractionMode"
          default: NORMAL
      required:
        - interactionId
        - interactionDate
        - applicationName
        - interfaceName
        - methodName
        - interactionMode
    InteractionStartedEvent:
      allOf:
        - $ref: "#/components/schemas/InteractionEvent"
        - type: object
          properties:
            systemMessage:
              type: string
            userMessage:
              type: string
          required:
            - userMessage
    InteractionCompletedEvent:
      allOf:
        - $ref: "#/components/schemas/InteractionEvent"
        - type: object
          properties:
            result:
              type: string
    UUID:
      type: string
      format: uuid
    InteractionScore:
      type: object
      properties:
        interactionId:
          $ref: "#/components/schemas/UUID"
        interactionDate:
          $ref: "#/components/schemas/Instant"
        scoreDate:
          $ref: "#/components/schemas/Instant"
        score:
          type: number
          format: double
        interactionMode:
          $ref: "#/components/schemas/InteractionMode"
    InteractionMode:
      type: string
      enum:
        - NORMAL
        - RESCORE
    Interactions:
      type: object
      properties:
        interactions:
          type: array
          items:
            $ref: "#/components/schemas/Interaction"
    Interaction:
      type: object
      properties:
        interactionId:
          $ref: "#/components/schemas/UUID"
        interactionDate:
          $ref: "#/components/schemas/Instant"
        applicationName:
          type: string
        interfaceName:
          type: string
        methodName:
          type: string
        systemMessage:
          type: string
        userMessage:
          type: string
        result:
          type: string
        scores:
          type: array
          items:
            $ref: "#/components/schemas/InteractionScore"
      required:
        - interactionId
        - interactionDate
        - applicationName
        - interfaceName
        - methodName
paths:
  /ai/interactions:
    get:
      parameters:
        - name: applicationName
          in: query
          required: false
          schema:
            type: string
        - name: interfaceName
          in: query
          required: false
          schema:
            type: string
        - name: methodName
          in: query
          required: false
          schema:
            type: string
        - name: start
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/Instant"
        - name: end
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/Instant"
      responses:
        "200":
          description: List of interactions found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Interactions"
        "400":
          description: Bad Request
        "404":
          description: No interactions found
        "500":
          description: Something bad happened
      summary: Search for interactions
      operationId: findInteractions
      tags:
        - AIInteractions
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InteractionEvent"
      responses:
        "200":
          description: Successful response for an InteractionCompletedEvent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InteractionScore"
        "204":
          description: Successful response for an InteractionStartedEvent
        "400":
          description: Bad Request
        "500":
          description: Something bad happened
      summary: Submit AI Interaction Event
      operationId: submitInteractionEvent
      tags:
        - AIInteractions
  /ai/interactions/{uuid}:
    get:
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: Interaction found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InteractionEvent"
        "404":
          description: Interaction not found
        "500":
          description: Something bad happened
      summary: Get AI Interaction by UUID
      operationId: getInteractionById
      tags:
        - AIInteractions
info:
  title: AI Interactions
  version: "1.0"
  description: Contract for getting AI interactions
  contact:
    name: Eric Deandrea
    url: https://github.com/edeandrea