{
 "title": "AI Dashboard",
 "description": "Dashboard for Quarkus applications instrumented with the Micrometer to OpenTelemetry bridge.",
 "tags": [
  "AI",
  "Auditing",
  "OpenTelemetry",
  "Micrometer",
  "Quarkus",
  "Metrics"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{},job)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{  area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{  area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "AI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total AI Cost",
   "type": "stat",
   "description": "The total AI cost",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((((parasol_llm_token_input_count_tokens_total{modelName=\"gpt-5-mini-2025-08-07\"}/1000000)*0.25)+((parasol_llm_token_output_count_tokens_total{modelName=\"gpt-5-mini-2025-08-07\"}/1000000)*2)))",
     "legendFormat": "{{modelName}}"
    },
    {
     "expr": "((((parasol_llm_token_input_count_tokens_total{modelName=\"gpt-4o-mini-2024-07-18\"}/1000000)*0.15)+((parasol_llm_token_output_count_tokens_total{modelName=\"gpt-4o-mini-2024-07-18\"}/1000000)*0.60)))",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "Number of AI invocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "parasol_llm_initialmessages_created_messages_created_total{interfaceName!~\"\",methodName!~\"\"}",
     "legendFormat": "{{interfaceName}}.{{methodName}}"
    }
   ]
  },
  {
   "title": "LLM interaction failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "parasol_SERVICE_ERROR_failed_interactions_total or vector(0)",
     "legendFormat": "{{interfaceName}}.{{methodName}}"
    }
   ]
  },
  {
   "title": "Avg Guardrail executions / interaction",
   "type": "timeseries",
   "description": "Average number of guardrail executions per interaction",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "parasol_llm_guardrail_output_executed_executed_output_guardrails_total{interfaceName=\"org.parasol.ai.GenerateEmailService\",methodName=\"generateEmail\"} / parasol_llm_initialmessages_created_messages_created_total{interfaceName=\"org.parasol.ai.GenerateEmailService\",methodName=\"generateEmail\"}",
     "legendFormat": "GenerateEmailService.generateEmail"
    },
    {
     "expr": "(parasol_llm_guardrail_output_executed_executed_output_guardrails_total{interfaceName=\"org.parasol.ai.ClaimService\",methodName=\"chat\"} / parasol_llm_initialmessages_created_messages_created_total{interfaceName=\"org.parasol.ai.ClaimService\",methodName=\"chat\"}) or vector(0)",
     "legendFormat": "ClaimService.chat"
    },
    {
     "expr": "(parasol_llm_guardrail_output_executed_executed_output_guardrails_total{interfaceName=\"org.parasol.ai.guardrail.PolitenessService\",methodName=\"isPolite\"} / parasol_llm_initialmessages_created_messages_created_total{interfaceName=\"org.parasol.ai.guardrail.PolitenessService\",methodName=\"isPolite\"}) or vector(0)",
     "legendFormat": "PolitenessService.isPolite"
    }
   ]
  },
  {
   "title": "Number of tool invocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "parasol_llm_tool_executed_executed_tools_total{toolName!~\"\"}",
     "legendFormat": "{{toolName}}"
    }
   ]
  },
  {
   "title": "Token counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "parasol_llm_token_input_count_tokens_total{modelName!~\"\"}",
     "legendFormat": "Input tokens ({{modelName}})"
    },
    {
     "expr": "parasol_llm_token_output_count_tokens_total{modelName!~\"\"}",
     "legendFormat": "Output tokens ({{modelName}})"
    },
    {
     "expr": "parasol_llm_token_count_tokens_total{modelName!~\"\"}",
     "legendFormat": "Total tokens ({{modelName}})"
    }
   ]
  },
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Heap used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{ area = \"heap\", job = \"$instance\"}) * 100 / sum(jvm_memory_max_bytes{ area = \"heap\", job = \"$instance\" })"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{ area = \"nonheap\", job = \"$instance\" }) * 100 / sum(jvm_memory_max_bytes{ area = \"nonheap\", job = \"$instance\" })"
    }
   ]
  },
  { "title": "HTTP Edpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_milliseconds{ job = \"$instance\" } / 1000"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_milliseconds{ job = \"$instance\" }"
    }
   ]
  },
  {
   "title": "Average inbound request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_milliseconds_sum{ job = \"$instance\" }[4m]) / rate(http_server_requests_milliseconds_count{ job = \"$instance\" }[4m]) / 1000",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Total number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate( http_server_requests_milliseconds_count{ job = \"$instance\" }[2m]) * 120",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Sum of the duration of every request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_milliseconds_sum{ job = \"$instance\" }[2m])) / 1000",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Maximum inbound request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_max_milliseconds{ job = \"$instance\" } / 1000",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{ job = \"$instance\" })",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{ job = \"$instance\" })",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{ job = \"$instance\" })",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{ area = \"heap\", job = \"$instance\" })",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{ area = \"heap\", job = \"$instance\" })",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{ area = \"heap\", job = \"$instance\" })",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{ area = \"nonheap\", job = \"$instance\" })",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{ area=\"nonheap\", job = \"$instance\" })",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{ area=\"nonheap\", job = \"$instance\" })",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{ job = \"$instance\" }",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{ job = \"$instance\" }",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{ job = \"$instance\" }[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{ job = \"$instance\" }",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{ job = \"$instance\" }",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states{ job = \"$instance\" }",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live{ job = \"$instance\" }",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon{ job = \"$instance\" }",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{ job = \"$instance\" }",
     "legendFormat": "peak"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_files_open{ job = \"$instance\" }",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max{ job = \"$instance\" }",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JDBC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "JDBC Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "agroal_active_count{ job = \"$instance\" }",
     "legendFormat": "Active Connections"
    },
    {
     "expr": "agroal_available_count{ job = \"$instance\" }",
     "legendFormat": "Available Connections"
    },
    {
     "expr": "rate(agroal_leak_detection_count_total{ job = \"$instance\" }[$__rate_interval])",
     "legendFormat": "Leaked Connections"
    }
   ]
  },
  {
   "title": "JDBC Blocking Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "agroal_blocking_time_average_milliseconds{ job = \"$instance\" }",
     "legendFormat": "Average (ms)"
    },
    {
     "expr": "agroal_blocking_time_max_milliseconds{ job = \"$instance\" }",
     "legendFormat": "Max (ms)"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 }, "repeat": "persistence_counts" },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "repeat": "jvm_memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{ id =~ \"$jvm_memory_pool_heap\", job = \"$instance\" }",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{ id =~ \"$jvm_memory_pool_heap\", job = \"$instance\" }",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{ id =~ \"$jvm_memory_pool_heap\", job = \"$instance\" }",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "repeat": "jvm_memory_pool_nonheap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{ id =~ \"$jvm_memory_pool_nonheap\", job = \"$instance\" }",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{ id =~ \"$jvm_memory_pool_nonheap\", job = \"$instance\" }",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{ id =~ \"$jvm_memory_pool_nonheap\", job = \"$instance\" }",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_milliseconds_count{ job = \"$instance\" }[2m]) * 120",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(jvm_gc_pause_milliseconds_sum{ job = \"$instance\" }[2m]) / rate(jvm_gc_pause_milliseconds_count{ job = \"$instance\" }[2m])) / 1000",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_milliseconds_max{ job = \"$instance\" } / 1000",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{ job = \"$instance\" }[2m]) * 120",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{ job = \"$instance\" }[2m]) * 120",
     "legendFormat": "promoted"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded{ job = \"$instance\" }",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded{ job = \"$instance\" }[2m])",
     "legendFormat": "delta-2m"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{ id = \"direct\", job = \"$instance\" }",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{ id = \"direct\", job = \"$instance\" }",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{ id = \"direct\", job = \"$instance\" }",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{ id = \"mapped\", job = \"$instance\" }",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{ id = \"mapped\", job = \"$instance\" }",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{ id = \"mapped\", job = \"$instance\" }",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "GraphQL requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of GraphQL requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(mp_graphql_seconds_count{ job = \"$instance\" }[2m])",
       "legendFormat": "{{type}} {{name}}"
      }
     ]
    },
    {
     "title": "Average inbound request duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(mp_graphql_seconds_sum{ job = \"$instance\" }[4m]) / rate(mp_graphql_seconds_count{ job = \"$instance\" }[4m])",
       "legendFormat": "{{type}} {{name}}"
      }
     ]
    },
    {
     "title": "Maximum inbound GraphQL request duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 183 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "mp_graphql_seconds_max{ job = \"$instance\" }",
       "legendFormat": "{{type}} {{name}}"
      }
     ]
    },
    {
     "title": "Sum of the duration of every GraphQL request",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 183 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(mp_graphql_seconds_sum{ job = \"$instance\" }[2m])",
       "legendFormat": "{{type}} {{name}}"
      }
     ]
    }
   ]
  }
 ]
}