package org.parasol.claim.model;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Optional;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Table;

import org.hibernate.KeyType;
import org.hibernate.Length;
import org.hibernate.annotations.ColumnDefault;
import org.hibernate.annotations.NaturalId;

import io.quarkus.hibernate.orm.panache.PanacheEntity;

/**
 * An insurance claim. The REST API never serializes this entity; it returns the {@code ClaimDetails} DTO instead.
 */
@Entity
@Table(name = "claims")
public class Claim extends PanacheEntity {
	/**
	 * Generated by the database on insert (see {@link ClaimNumberGenerator}) and immutable afterwards. Never set it:
	 * the value is ignored on insert, and changing it on a managed claim fails the flush. It's only populated after the
	 * insert is flushed.
	 */
	@NaturalId
	@ClaimNumber
	@ColumnDefault(ClaimNumberGenerator.COLUMN_DEFAULT)
	@Column(unique = true, nullable = false, updatable = false)
	public String claimNumber;

	@Enumerated(EnumType.STRING)
	public ClaimCategory category;

	public String policyNumber;
	public LocalDate inceptionDate;
	public String clientName;

	@Column(length = Length.LONG32)
	public String subject;

	@Column(length = Length.LONG32)
	public String body;

	@Column(length = 5000)
	public String summary;

	@Column(length = Length.LONG32)
	public String location;

	public LocalDate incidentDate;
	public LocalTime incidentTime;

	@Column(length = 5000)
	public String sentiment;

	public String emailAddress;
	public String status;

	public static Optional<Claim> findByClaimNumber(String claimNumber) {
		return Optional.ofNullable(claimNumber)
			.map(number -> getSession().find(Claim.class, number, KeyType.NATURAL));
	}

}
